### ISSUE TITLE
Undefined index: overlay

### ISSUE THREAD

**Issue by darkgoldblade01** [laracasts/flash#98] opened 2017-05-10 22:23 UTC
I am getting errors on an installation that I didn't before.

`Undefined index: overlay`

If I change the view from `@if ($message['overlay'])` to `@if (isset($message['overlay']))`, it works, but then goes down to `Undefined index: level`.

Any insight as to why this would be the case?

**Comment by davidpaulalbert** [comment] 2017-06-20 19:50
Same issue here. Laravel 5.4

**Comment by phpfalcon** [comment] 2017-06-21 03:43
chagne 

> message.blade.php

 file to : 
```php
@foreach ((array) session('flash_notification') as $message)
@php $message = (array)$message[0]; @endphp
    @if ($message['overlay'])
        @include('flash::modal', [
            'modalClass' => 'flash-modal',
            'title'      => $message['title'],
            'body'       => $message['message']
        ])
    @else
        <div class="alert
                    alert-{{ $message['level'] }}
                    {{ $message['important'] ? 'alert-important' : '' }}"
                    role="alert"
        >
            @if ($message['important'])
                <button type="button"
                        class="close"
                        data-dismiss="alert"
                        aria-hidden="true"
                >&times;</button>
            @endif

            {!! $message['message'] !!}
        </div>
    @endif
@endforeach

{{ session()->forget('flash_notification') }}
```

**Comment by stus3y** [comment] 2017-06-21 05:52
it works!

**Comment by davidpaulalbert** [comment] 2017-06-21 15:56
Worked for me as well. Thank you!

**Comment by badluckvlad** [comment] 2017-06-22 13:33
Well the answer works but sadly it only takes into consideration the first flash message, if you have multiple messages then you're in trouble. 
The real fix and making this working "as intended is to edit the same file (aka message.blade.php) and on the first line change from 
`@foreach ((array) session('flash_notification') as $message)`
to 
`@foreach (session('flash_notification')->toArray() as $message)`ow everything works perfectly

**Comment by Noramarth** [comment] 2017-06-22 13:34
Well the answer works but sadly it only takes into consideration the first flash message, if you have multiple messages then you're in trouble. 
The real fix and making this working "as intended is to edit the same file (aka message.blade.php) and on the first line change from 
`@foreach ((array) session('flash_notification') as $message)`
to 
`@foreach (session('flash_notification')->toArray() as $message)`ow everything works perfectly

**Comment by simonschaufi** [comment] 2017-06-22 14:46
I think the last release came a little bit too early as I also have this problem since upgrade from 3.0.0 to 3.0.1

**Comment by ruchern** [comment] 2017-06-22 14:47
@simonschaufi `v3.0.1` update has nothing related to stuff changed in `v3.0.0`. `v3.0.1` is for Laravel's 5.5 automatic package discovery.

**Comment by simonschaufi** [comment] 2017-06-22 14:55
With 3.0.0 i don't have this bug! I just confirmed it. Changed `"laracasts/flash": "3.0.0",` in my composer and did composer update and it works again.

**Comment by ruchern** [comment] 2017-06-22 14:56
Okay, that is weird. The only code changed from 3.0.0 to 3.0.1 is to add the package discovery and that's all.

**Comment by simonschaufi** [comment] 2017-06-22 14:57
Nop. Check the diff: https://github.com/laracasts/flash/compare/3.0.0...3.0.1

**Comment by dbpolito** [comment] 2017-06-22 17:08
Opened a PR with a fix for this: https://github.com/laracasts/flash/issues/98

**Closed** 2017-06-22 19:01 UTC

**Comment by jkisanga** [comment] 2017-11-06 21:47
kwangu imekubali. asante

**Comment by feisepulveda** [comment] 2018-08-29 13:58
@if4lcon Muchas gracias, Funciono!!!!!
