### ISSUE TITLE
Flash doesn't appearing

### ISSUE THREAD

**Issue by avescasio** [laracasts/flash#60] opened 2016-04-12 03:37 UTC
Flash message seems not appearing, I use the Laravel ver.5.2

In my composer for reference:
`{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "acacha/admin-lte-template-laravel": "2.0.7",
        "doctrine/dbal": "2.3.5",
        "barryvdh/laravel-ide-helper": "v2.1.4",
        "laravelcollective/html": "v5.2.4",
        "infyomlabs/laravel-generator": "dev-master",
        "infyomlabs/core-templates": "dev-master",
        "infyomlabs/swagger-generator": "dev-master",
        "barryvdh/laravel-debugbar": "v2.2.0",
        "davejamesmiller/laravel-breadcrumbs": "3.0.0"
    },`

in my IndustryController.php
`    public function store(Request $request)
    {
        $industry = new Industrytype;
        $industry->name = $request['name'];
        $industry->description = $request['description'];
        $industry->save();
        flash()->success('Save Successfully');
        return redirect('industry');`

in app.blade.php
`    
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        
        <section class="content">
            @include('flash::message')
            
            @yield('main-content')
        </section>

    </div>`

also added the ServiceProvider in app.php
` 
'providers' => [
               Laracasts\Flash\FlashServiceProvider::class,
],

'aliases' => [
             'Flash' => Laracasts\Flash\Flash::class,
],
`

**Comment by pallmallshow** [comment] 2016-04-12 14:27
Hi,

I had the same problem.
When I set a flash message just before a redirect, the flash message in session disappeared.

In package src, on FlashNotifier.php, I display a debug of session attributes in message function, just before the return. No problem, data are stored.

But after the redirection, the flash array in session data is just empty.

I'm trying to make a PR if I found the bug.

**Comment by chaotixlv** [comment] 2016-04-14 20:32
What about "industry" section, is there any inner redirect? Because flash messages are alive only for 1 request

**Comment by avescasio** [comment] 2016-04-15 08:16
I use the AdminLTE as my template layout, even in app.blade.php flashing there doesn't appear. I don't have any inner redirect in my industry section.

**Comment by mansouralex** [comment] 2016-04-16 14:27
@avescasio does the `web ` middleware assigned to route that you are facing the issue with?

**Comment by avescasio** [comment] 2016-04-18 05:10
Hi @mansouralex 

This is my codes in my routes: 

`Route::group(['middlewareGroups' => ['web']], function ()
{
    Route::resource('industry' , 'IndustryController' );
}`

**Comment by mansouralex** [comment] 2016-04-18 05:21
You need to change middlewareGroups to middleware See: [https://laravel.com/docs/5.2/middleware#middleware-groups](https://laravel.com/docs/5.2/middleware#middleware-groups)

**Comment by pallmallshow** [comment] 2016-04-18 12:40
Maybe I'm wrong, but the RoutesServiceProvider has changed. So I removed "web" middleware on my routes, and all flash appears and validation errors too.
To be confirmed !

**Comment by srmklive** [comment] 2016-04-20 07:03
i have a package similar to this one ... https://github.com/srmklive/flash-notifications ... may be you guys can give it a try as well

**Comment by avescasio** [comment] 2016-04-27 08:52
Got it now:

To resolve put your route in middleware

Route::group(['middleware' => 'web'], function ()
{
    put here: Route::resource...

});

in 5.2.29 v it will give you: Fatal error: Maximum function nesting level of '100' reached

to resolve this above statement: in bootstrap / autoload.php

set the max_nesting_level ini_set('xdebug.max_nesting_level',500);

**Closed** 2016-04-27 08:54 UTC
